version: '3'

services:
  api:
    build: .
    container_name: node-auth-api
    image: node-auth-api
    volumes:
      - .:/src
    tty: true
    expose:
      - "3000"
    ports:
      - "3000:3000"
    env_file: .env
    links:
      - database:database
    depends_on:
      - database
    command: ["npm", "start"]

  database:
    container_name: node-auth-db
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"